---
## Playbook to show version on IOS

- hosts: localhost

  tasks:
    - name: Get ansible dte/time facts
      setup:
        filter: "ansible date time"
        gather subset: "!all"

    - name: store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"
    
    - name: Create directory {{hostvars.localhost.TDG}}
      file:
        path: ~/afne/backups/{{hostvars.localhost.DTG}}
        state: directory
  run_once: true

- hosts: CSR_Routers

  tasks:
  - name: Backup config
    ios_command:
      commands: show run
    register: config

  - name: Save output to ~/afne/backups/{{hostvars.localhost.TDG}}
    copy:
      content: "{{config.stdout[0]}}"
      dest: "~/afne/backups/{{hostvars.localhost.TDG}}/{{inventory_hostname}}-{{hostvars.localhost.TDG}}.txt"